const PrivacyPolicyEnglish = `
This privacy policy (“Policy”) describes how GP Wallet(“GP Wallet” “Company”, “we”, “our”, “us”) collects, uses, shares, and stores personal information of users of this application and the Services (as defined below).. This Policy applies to the Site, applications, products and services (collectively, “Services”) on or in which it is posted, linked, or referenced.
By using the Services, you accept the terms of this Policy and our Terms of Use, and consent to our collection, use, disclosure, and retention of your information as described in this Policy.  If you have not done so already, please also review our terms of use. The terms of use contain provisions that limit our liability to you and require you to resolve any dispute with us on an individual basis and not as part of any class or representative action. IF YOU DO NOT AGREE WITH ANY PART OF THIS PRIVACY POLICY OR OUR TERMS OF USE, THEN PLEASE DO NOT USE ANY OF THE SERVICES.
Please note that this Policy does not apply to information collected through third-party websites or services that you may access through the Services or that you submit to us through email, text message or other electronic message or offline.
If you are visiting this site from the European Union (EU), see our Notice to EU Data Subjects for our legal bases for processing and transfer of your data.
WHAT WE COLLECT
We get information about you in a range of ways.
Information You Give Us. Information we collect from you includes: ‍
* Public address (decentralized identifier);
* Private key signature associated with your DID (as defined in the Terms of Use) for transactions you engage in with the Services 
* Identity information, such as your first name, last name, username or similar identifier, title, date of birth and nationality; 
* Feedback and correspondence, such as information you provide in your responses to surveys, when you participate in market research activities, report a problem with Service, receive customer support or otherwise correspond with us;
* Transaction information, such as metadata with respect to on-chain transaction history,  details about purchases you make through the Service and billing details;
* Anonymized usage information, such as information about how you use the Service and interact with us; and
* Marketing information, such as your preferences for receiving marketing communications and details about how you engage with them.
Information We Get From Others. We may get information about you from other third party sources and we may add this to information we get from your use of the Services.
Information Automatically Collected. We may automatically record certain information about how you use our Site (we refer to this information as “Log Data“). Log Data may include information such as a user’s Internet Protocol (IP) address, hash of IPFS address, device and browser type, the pages or features of our Site to which a user browsed and the time spent on those pages or features, the frequency with which the Site is used by a user, search terms, the links on our Site that a user clicked on or used, referral url, and other statistics. We use this information to administer the Service and we analyze (and may engage third parties to analyze) this information to improve and enhance the Service by expanding its features and functionality and tailoring it to our users’ needs and preferences.
We may use cookies or similar technologies to analyze trends, administer the website, track users’ movements around the website, and to gather demographic information about our user base as a whole. Users can control the use of cookies at the individual browser level. For more information, please see the section entitled “Cookies Policy” below.
We also use data analytics services such as Google Analytics, Fabric, and Mixpanel to help us offer you an optimized user experience. You can find more information about Google Analytics’ use of your personal data here: https://www.google.com/analytics/terms/us.html. You can find more information about Fabric’s use of your personal data here: https://policies.google.com/privacy?hl=en&gl=us. You can find more information about Mixpanel’s use of your personal data here: https://mixpanel.com/legal/privacy-policy/.
Information we will never collect. We will never ask you to share your private keys or wallet seed. Never trust anyone or any site that asks you to enter your private keys or wallet seed.
USE OF PERSONAL INFORMATION
To provide our service ‍We will use your personal information in the following ways:
* To enable you to access and use the Services
* To provide and deliver products and services that you may request.
* To send information, including confirmations, technical notices, updates, security alerts, and support and administrative messages.
To comply with law ‍We use your personal information as we believe necessary or appropriate to comply with applicable laws,  lawful requests and legal process, such as to respond to subpoenas or requests from government authorities.  
To communicate with you ‍We use your personal information to communicate about promotions, upcoming events, and other news about products and services offered by us and our selected partners.
To optimize our platform ‍In order to optimize your user experience, we may use your personal information to operate, maintain, and improve our Services. We may also use your information to respond to your comments and questions regarding the Services, and to provide you and other users with general customer service.
With your consent ‍We may use or share your personal information with your consent, such as when you instruct us to take a specific action with respect to your personal information, or you opt into third party marketing communications.
For compliance, fraud prevention, and safety ‍We may use your personal information to protect, investigate, and deter against fraudulent, unauthorized, or illegal activity.
SHARING OF PERSONAL INFORMATION
We do not share or sell the personal information that you provide us with other organizations without your express consent, except as described in this Privacy Policy. We disclose personal information to third parties under the following circumstances:
Affiliates. We may disclose your personal information to our subsidiaries and corporate affiliates for purposes consistent with this Privacy Policy.
Business Transfers. We may share personal information when we do a business deal, or negotiate a business deal, involving the sale or transfer of all or a part of our business or assets. These deals can include any merger, financing, acquisition, or bankruptcy transaction or proceeding.
Compliance with Laws and Law Enforcement; Protection and Safety. We may share personal information for legal, protection, and safety purposes.
* We may share information to comply with laws.
* We may share information to respond to lawful requests and legal processes.
* We may share information to protect the rights and property of the Company, our agents, customers, and others. This includes enforcing our agreements, policies, and terms of use.
* We may share information in an emergency. This includes protecting the safety of our employees and agents, our customers, or any person.
Professional Advisors and Service Providers. We may share information with those who need it to do work for us. These recipients may include third party companies and individuals to administer and provide the Service on our behalf (such as customer support, hosting, email delivery and database management services), as well as lawyers, bankers, auditors, and insurers.
If you are visiting this site from the European Union (EU), see our Notice to EU Data Subjects for our legal bases for processing and transfer of your data.
INTERNATIONAL TRANSFER
The Company has offices outside of the EU and has affiliates and service providers in the United States and in other countries. Your personal information may be transferred to or from the United States or other locations outside of your state, province, country or other governmental jurisdiction where privacy laws may not be as protective as those in your jurisdiction.
EU users should read the important information provided belowabout transfer of personal information outside of the European Economic Area (EEA).
HOW INFORMATION IS SECURED
We retain information we collect as long as it is necessary and relevant to fulfill the purposes outlined in this privacy policy. In addition, we retain personal information to comply with applicable law where required, prevent fraud, resolve disputes, troubleshoot problems, assist with any investigation, enforce our Terms of Use, and other actions permitted by law. To determine the appropriate retention period for personal information, we consider the amount, nature, and sensitivity of the personal information, the potential risk of harm from unauthorized use or disclosure of your personal information, the purposes for which we process your personal information and whether we can achieve those purposes through other means, and the applicable legal requirements.
In some circumstances we may anonymize your personal information (so that it can no longer be associated with you) in which case we may use this information indefinitely without further notice to you.
We employ industry standard security measures designed to protect the security of all information submitted through the Services. However, the security of information transmitted through the internet can never be guaranteed. We are not responsible for any interception or interruption of any communications through the internet or for changes to or losses of data. Users of the Services are responsible for maintaining the security of any password, biometrics, user ID or other form of authentication involved in obtaining access to password protected or secure areas of any of our digital services. In order to protect you and your data, we may suspend your use of any of the Services, without notice, pending an investigation, if any breach of security is suspected.
INFORMATION CHOICES AND CHANGES
Accessing, Updating, Correcting, and Deleting your InformationYou may access information that you have voluntarily provided through your account on the Services, and to review, correct, or delete it by sending a request toinfo@faglobalbkfinance.com. You can request to change contact choices, opt-out of our sharing with others, and update your personal information and preferences.
Tracking Technologies GenerallyRegular cookies may generally be disabled or removed by tools available as part of most commercial browsers, and in some instances blocked in the future by selecting certain settings. For more information, please see the section entitled “Cookies Policy” below.
Google AnalyticsYou may exercise choices regarding the use of cookies from Google Analytics by going to https://tools.google.com/dlpage/gaoptout and downloading the Google Analytics Opt-out Browser Add-on.
CONTACT INFORMATION. We welcome your comments or questions about this Policy, and you may contact us at:info@faglobalbkfinance.com.
CHANGES TO THIS PRIVACY POLICY. We may change this privacy policy at any time. We encourage you to periodically review this page for the latest information on our privacy practices. If we make any changes, we will change the Last Updated date above.
Any modifications to this Privacy Policy will be effective upon our posting of the new terms and/or upon implementation of the changes to the Site (or as otherwise indicated at the time of posting). In all cases, your continued use of the the Site or Services after the posting of any modified Privacy Policy indicates your acceptance of the terms of the modified Privacy Policy.
ELIGIBILITY
If you are under the age of majority in your jurisdiction of residence, you may use the Services only with the consent of or under the supervision of your parent or legal guardian. Consistent with the requirements of the Children's Online Privacy Protection Act (COPPA), if we learn that we have received any information directly from a child under age 13 without first receiving his or her parent's verified consent, we will use that information only to respond directly to that child (or his or her parent or legal guardian) to inform the child that he or she cannot use the Site and subsequently we will delete that information.
NOTICE TO CALIFORNIA RESIDENTS
Under California Civil Code Section 1789.3, California users are entitled to the following consumer rights notice: California residents may reach the Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs by mail at 1625 North Market Blvd., Sacramento, CA 95834, or by telephone at (916) 445-1254 or (800) 952-5210.
Personal Information ‍With respect to EU data subjects, “personal information,” as used in this Privacy Policy, is equivalent to“personal data” as defined in the European Union General Data Protection Regulation (GDPR).
Sensitive Data ‍Some of the information you provide us may constitute sensitive data as defined in the GDPR (also referred to as special categories of personal data), including identification of your race or ethnicity on government-issued identification documents.
Legal Bases for Processing We only use your personal information as permitted by law. We are required to inform you of the legal bases of our processing of your personal information, which are described in the table below. If you have questions about the legal bases under which we process your personal information, contact us at info@dde-ex.com.
Processing Purpose
Legal Basis
To communicate with you  To optimize our platform
These processing activities constitute our legitimate interests. We make sure we consider and balance any potential impacts on you (both
To communicate with you  For compliance, fraud prevention, and safetyTo provide our service
positive and negative) and your rights before we process your personal information for our legitimate interests. We do not use your personal information for activities where our interests are overridden by any adverse impact on you (unless we have your consent or are otherwise required or permitted to by law).
To comply with law
We use your personal information to comply with applicable laws and our legal obligations.
With your consent
We use your personal information to comply with applicable laws and our legal obligations.Where our use of your personal information is based upon your consent, you have the right to withdraw it anytime in the manner indicated in the Service or by contacting us at info@dde-ex.com.
Use for New Purposes
We may use your personal information for reasons not described in this Privacy Policy, where we are permitted by law to do so and where the reason is compatible with the purpose for which we collected it. If we need to use your personal information for an unrelated purpose, we will notify you and explain the applicable legal basis for that use. If we have relied upon your consent for a particular use of your personal information, we will seek your consent for any unrelated purpose.
Your Rights
Under the GDPR, you have certain rights regarding your personal information. You may ask us to take the following actions in relation to your personal information that we hold:
* Opt-out. Stop sending you direct marketing communications which you have previously consented to receive. We may continue to send you Service-related and other non-marketing communications.
* Access. Provide you with information about our processing of your personal information and give you access to your personal information.
* Correct. Update or correct inaccuracies in your personal information.
* Transfer. Transfer a machine-readable copy of your personal information to you or a third party of your choice.
* Restrict. Restrict the processing of your personal information.
* Object. Object to our reliance on our legitimate interests as the basis of our processing of your personal information that impacts your rights.
You can submit these requests by email toinfo@faglobalbkfinance.com. We may request specific information from you to help us confirm your identity and process your request. Applicable law may require or permit us to decline your request. If we decline your request, we will tell you why, subject to legal restrictions. If you would like to submit a complaint about our use of your personal information or response to your requests regarding your personal information, you may contact us atinfo@faglobalbkfinance.com or submit a complaint to the data protection regulator in your jurisdiction. You can find your data protection regulator here.
Cross-Border Data Transfer
Please be aware that your personal data will be transferred to, processed, and stored in the United States. Data protection laws in the U.S. may be different from those in your country of residence. You consent to the transfer of your information, including personal information, to the U.S. as set forth in this Privacy Policy by visiting our site or using our service.
Whenever we transfer your personal information out of the EEA to the U.S. or countries not deemed by the European Commission to provide an adequate level of personal information protection, the transfer will be based on a data transfer mechanism recognized by the European Commission as providing adequate protection for personal information.
Please contact us if you want further information on the specific mechanism used by us when transferring your personal information out of the EEA.
`;

// max-len
const TermsOfUseEnglish = `
GP Wallet, a product of  (“GP Wallet”, “we”, “our”, or “us”) provides a platform for self-sovereign digital identity management through our website located at this application and a mobile application.  The mobile application includes text, images, audio, code and other materials or third party applications accessible through the GP Wallet application (collectively, with the Site, the “Content”). The Site, the mobile app, and any other features, tools, materials, or other services offered from time to time by GP Wallet are referred to here as the “Service.”
1. Acceptance of Terms
Please read these Terms of Use (the “Terms”) carefully before using the Service. By using or otherwise accessing the Services, or clicking to accept these Terms, you (a) accept and agree to these Terms (b) consent to the collection, use, disclosure and other handling of information as described in our Privacy Policy and (c) agree to any additional terms, rules and conditions of participation issued by GP Wallet from time to time. IF YOU DO NOT AGREE TO THE TERMS, AS AMENDED FROM TIME TO TIME AS SET FORTH BELOW, YOU MUST STOP USING THE SERVICE IMMEDIATELY.
2. Modification of Terms
GP Wallet reserves the right, at its sole discretion, to modify or replace the Terms at any time. The most current version of these Terms will be posted on our Site. You shall be responsible for reviewing and becoming familiar with any such modifications. Use of the Services by you after any modification to the Terms constitutes your acceptance of the Terms as modified.
3. Eligibility
You hereby represent and warrant that you are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations and warranties set forth in these Terms and to abide by and comply with these Terms. By accessing the Content or Services, you represent and warrant that you are of the legal age of majority in your jurisdiction or of the age required to access such Services and Content. You further represent that you are otherwise legally permitted to use the service in your jurisdiction including owning cryptographic tokens of value, and interacting with the Services or Content in any way. You further represent you are responsible for ensuring compliance with the laws of your jurisdiction and acknowledge that GP Wallet is not liable for your compliance with such laws.
4. Account Password, Security, and Decentralized Identity (DID)
Password/Seed
When setting up an account within GP Wallet, you will be responsible for keeping your own account secrets private. These secrets may include your designated recovery network, a twelve-word seed phrase, or other security features.  You acknowledge your understanding that any person with knowledge of your seed phrase may generate your private keys.  You further acknowledge that GP Wallet does not own your private keys or the seed phrase.  GP Wallet has no ability to recover your private keys or your seed phrase should they become lost.
Security
Your private key, corresponding to your public Ethereum identity address is stored in the keychain controlled by the “secure enclave” of your device.  By using the GP Wallet app, you shall institute proper and sufficient password or biometric protection within your device.  You shall regularly update the operating system of your device with any software or security updates.  Notwithstanding the foregoing, you acknowledge that the GP Wallet app, which exists outside of the “secure enclave,” when initiated by the User, uses the private key information stored in the keychain for relevant signing activities.  Your private key remains within the GP Wallet app and GP Wallet does not send the private key to servers.  You agree to (a) keep your secret information confidential and to not share it with anyone else; (b) not share your seed phrase with anyone and to store it in a secure manner; and (c) immediately notify GP Wallet of any unauthorized use of your account or breach of security. GP Wallet cannot and will not be liable for any loss or damage arising from your failure to comply with this section.  
DID
By using the GP Wallet app, you acknowledge, accept and consent to the creation of a decentralized identity (DID) for you.  DID is essentially a public address, a string that serves asan “on-chain identifier.”  Because GP Wallet is an identity platform on the Ethereum blockchain,  DIDs are linked to the Ethereum blockchain as transactions.  As a user of GP Wallet, you acknowledge that because transactions on the Ethereum blockchain are immutable, the record of your DID’s on-chain transactions are also immutable and cannot be deleted from the Ethereum blockchain.  Your DID, as it is designed in the GP Wallet mobile application, is not tied to your natural name or personal information, and GP Wallet does not collect data that would enable the two to be linked or associated together.
5. Representations, Warranties, and Risks
5.1. Warranty Disclaimer
You expressly understand and agree that your use of the Service is at your sole risk. The Service (including the Service and the Content) is provided on an "AS IS" and "as available" basis, without warranties of any kind, either express or implied, including, without limitation, implied warranties of merchantability, fitness for a particular purpose or non-infringement. You acknowledge that GP Wallet has no control over, and no duty to take any action regarding: which users gain access to or use the Service; what affects the Content may have on you; how you may interpret or use the Content; or what actions you may take as a result of having been exposed to the Content. You release GP Wallet from all liability for you having acquired or not acquired Content through the Service. GP Wallet makes no representations concerning any Content contained in or accessed through the Service, and GP Wallet will not be responsible or liable for the accuracy, copyright compliance, legality or decency of material contained in or accessed through the Service.
5.2. Sophistication and Risk of Cryptographic Systems
By utilizing the Service or interacting with the Content in any way, you represent and warrant that you understand (a) the inherent risks associated with cryptographic systems, and (b) the usage and intricacies of public/private key cryptography, native cryptographic tokens, like Ether (ETH) and Bitcoin (BTC), smart contract based tokens such as those that follow the Ethereum Token Standard (https://github.com/ethereum/EIPs/issues/20), and blockchain-based software systems.
5.3. Risk of Weaknesses or Exploits in the Field of Cryptography
You acknowledge and understand that Cryptography is a progressing field. Advances in code cracking or technical advances such as the development of quantum computers may present risks to cryptographic systems and Services or Content, which could result in the theft or loss of your cryptographic tokens or property. To the extent possible, GP Wallet intends to update the code underlying the Services to account for any advances in cryptography and to incorporate additional security measures, but does not guarantee or otherwise represent full security of the system. By using the Service or accessing Content, you acknowledge these inherent risks.
5.4. Platform Security
You acknowledge that Ethereum applications are code subject to flaws and acknowledge that you are solely responsible for evaluating any available code provided by the Services or Content and the trustworthiness of any third-party websites, products, smart-contracts, or Content you access or use through the Service. You further expressly acknowledge and represent that Ethereum applications can be written maliciously or negligently, that GP Wallet cannot be held liable for your interaction with such applications and that such applications may cause loss of property or identity. Information relayed to IPFS and stored in contracts is currently unencrypted. Malicious actors may potentially access information such as name, photo, description, and members of your recovery network, presenting both disclosure and potential security risks. These warnings and others later provided by GP Wallet in no way evidence or represent an on-going duty to alert you to all of the potential risks of utilizing the Service or Content.
5.5. Risk of Regulatory Actions in One or More Jurisdictions
You acknowledge that as an emerging technology, GP Wallet or Ethereum could be impacted by one or more regulatory inquiries or regulatory actions, which could impede or limit the ability of GP Wallet to continue to develop, or which could impede or limit your ability to access or use the Service or Ethereum blockchain.
5.6. Risk of Errors, Bugs, and Downtime
You acknowledge and accept that the Services (a) may contain bugs, errors and defects, (b) may function improperly or be subject to periods of downtime and unavailability, (c) may result in total or partial loss or corruption of transaction data, and (d) may be modified at any time, including through the release of subsequent versions, in each case with or without notice.
5.7 Total Loss of Data
You acknowledge that GP Wallet did not manufacture your device.  The security of the security enclave of your device is dependent on the manufacturer of the device.  If you have reason to believe the security of your device’s security enclave has been compromised, you agree to stop the use of GP Wallet and to seek assistance directly with the device’s manufacturer.  You acknowledge the risk that if the security or integrity of your device’s security enclave is compromise, the security of your private key may be at risk.
GP Wallet does not own or operate the third-party servers used to store ID Data.  The security and safety of the data is dependent on the owner and operator of the third-party servers.  You acknowledge that in the event the security or integrity of the third-party servers are compromised, your ID Data may be completely or partially damaged and/or lost.    
6. Attestations on GP Wallet and the GP Wallet Signing Service
The Services may, from time to time, allow for various attestations to be made about a user. Unless otherwise specified, these attestations are independently made by third parties. uPort makes no representation or warranty regarding the veracity or accuracy of these third-party attestations. Third-party attestations may be subject to the attesting party's terms and conditions.
In some instances, third-party attestations may be made through the uPort Signing Service (“USS”). The USS allows a third-party to make an attestation about a particular user without that third-party directly making the attestation. Instead, the USS receives information about an attestation, and makes the attestation on behalf of a third party. uPort makes no representations as to the veracity or accuracy of attestations made through the USS and uPort hereby explicitly disclaims any and all liability pertaining to use of the USS for any purpose. 
uPort allows you to affirmatively opt-in and choose to send and store an encrypted copy of all your claims, attestations and corresponding associations of that information (“ID Data”) to your account that is stored in a service that is maintained by uPort and runs on servers and infrastructure owned and operated by third-party vendors. This means you will have the ability to recover ID Data but only after restoring the keys to your ID Data from your seed.  uPort does not back-up your private keys, only ID data. By opting in, you not only have the ability to back-up your ID data, but you can also delete all data on uPort’s open-sourced managed, third-party servers from within the mobile application.   You acknowledge that uPort is not responsible for the security or integrity of the third-party managed servers.
7. Indemnity
You agree to release and to indemnify, defend and hold harmless uPort and its parents, subsidiaries, affiliates and agencies, as well as the officers, directors, employees, shareholders and representatives of any of the foregoing entities, from and against any and all losses, liabilities, expenses, damages, costs (including attorneys’ fees and court costs) claims or actions of any kind whatsoever arising or resulting from your use of the Service, your violation of these Terms of Use, and any of your acts or omissions that implicate publicity rights, defamation or invasion of privacy. uPort reserves the right, at its own expense, to assume exclusive defense and control of any matter otherwise subject to indemnification by you and, in such case, you agree to cooperate with uPort in the defense of such matter.
8. Limitation on Liability
YOU ACKNOWLEDGE AND AGREE THAT YOU ASSUME FULL RESPONSIBILITY FOR YOUR USE OF THE SITE AND SERVICE. YOU ACKNOWLEDGE AND AGREE THAT ANY INFORMATION YOU SEND OR RECEIVE DURING YOUR USE OF THE SITE AND SERVICE MAY NOT BE SECURE AND MAY BE INTERCEPTED OR LATER ACQUIRED BY UNAUTHORIZED PARTIES. YOU ACKNOWLEDGE AND AGREE THAT YOUR USE OF THE SITE AND SERVICE IS AT YOUR OWN RISK. RECOGNIZING SUCH, YOU UNDERSTAND AND AGREE THAT, TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, NEITHER uPort NOR ITS SUPPLIERS OR LICENSORS WILL BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, EXEMPLARY OR OTHER DAMAGES OF ANY KIND, INCLUDING WITHOUT LIMITATION DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER TANGIBLE OR INTANGIBLE LOSSES OR ANY OTHER DAMAGES BASED ON CONTRACT, TORT, STRICT LIABILITY OR ANY OTHER THEORY (EVEN IF uPort HAD BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM THE SITE OR SERVICE; THE USE OR THE INABILITY TO USE THE SITE OR SERVICE; UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE SITE OR SERVICE; ANY ACTIONS WE TAKE OR FAIL TO TAKE AS A RESULT OF COMMUNICATIONS YOU SEND TO US; HUMAN ERRORS; TECHNICAL MALFUNCTIONS; FAILURES, INCLUDING PUBLIC UTILITY OR TELEPHONE OUTAGES; OMISSIONS, INTERRUPTIONS, LATENCY, DELETIONS OR DEFECTS OF ANY DEVICE OR NETWORK, PROVIDERS, OR SOFTWARE (INCLUDING, BUT NOT LIMITED TO, THOSE THAT DO NOT PERMIT PARTICIPATION IN THE SERVICE); ANY INJURY OR DAMAGE TO COMPUTER EQUIPMENT; INABILITY TO FULLY ACCESS THE SITE OR SERVICE OR ANY OTHER WEBSITE; THEFT, TAMPERING, DESTRUCTION, OR UNAUTHORIZED ACCESS TO, IMAGES OR OTHER CONTENT OF ANY KIND; DATA THAT IS PROCESSED LATE OR INCORRECTLY OR IS INCOMPLETE OR LOST; TYPOGRAPHICAL, PRINTING OR OTHER ERRORS, OR ANY COMBINATION THEREOF; OR ANY OTHER MATTER RELATING TO THE SITE OR SERVICE.
SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES. ACCORDINGLY, SOME OF THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.
9. Licenses and Access
Subject to your compliance with these Terms and your payment of any applicable fees, uPort grants you a limited, non-exclusive, non-transferable, non-sublicensable license to access and make personal and non-commercial use of the Service. This license does not include any resale or commercial use of the Service or any derivative use of the Service. All rights not expressly granted to you in these Terms are reserved and retained by uPort or its licensors. The uPort Service may not be reproduced, duplicated, copied, sold, resold, visited, or otherwise exploited for any commercial purpose without express written consent of uPort. You may not frame or utilize framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) of uPort without express written consent. You may not misuse the Services. You may use the Services only as permitted by law. The licenses granted by uPort terminate if you do not comply with these Terms. For more information regarding uPort’s licensors, uPort maintains this information on our attribution page found here: https://uPort.me/attributions
10. Links or Third Party Applications
The Service provides, or third parties may provide, links to other World Wide Web or accessible sites, applications or resources. Because uPort has no control over such sites, applications and resources, you acknowledge and agree that uPort is not responsible for the availability of such external sites, applications or resources, and does not endorse and is not responsible or liable for any content, advertising, products or other materials on or available from such sites or resources. You further acknowledge and agree that uPort shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such site or resource.
11. Termination and Suspension
uPort may, in its sole discretion, terminate or suspend all or part of the Service and your uPort access immediately, without prior notice or liability, if you breach any of the terms or conditions of the Terms. Upon termination of your access, your right to use the Service will immediately cease.
The following provisions of the Terms survive any termination of these Terms: INDEMNITY; WARRANTY DISCLAIMERS; LIMITATION ON LIABILITY; OUR PROPRIETARY RIGHTS; LINKS; TERMINATION; NO THIRD PARTY BENEFICIARIES; BINDING ARBITRATION AND CLASS ACTION WAIVER; GENERAL INFORMATION.
12. No Third Party Beneficiaries
You agree that, except as otherwise expressly provided in these Terms, (a) there shall be no third party beneficiaries to the Terms and (b) nothing in these Terms shall be construed as creating or implying any relationship of agency, franchise, partnership, or joint venture between you and uPort.
13. Notice and Procedure for Making Claims of Copyright Infringement
uPort responds to notices of alleged infringement. 
If you have a good faith belief that your work has been copied in a way that constitutes copyright infringement on or through the  Services, please send a notice of copyright infringement (“Notice”) to uPort via email to notices@consensys.net with attention to uPort Copyright. Please note that the uPort Privacy Policy does not protect information provided in a Notice. 
14. Binding Arbitration and Class Action Waiver
PLEASE READ THIS SECTION CAREFULLY – IT MAY SIGNIFICANTLY AFFECT YOUR LEGAL RIGHTS, INCLUDING YOUR RIGHT TO FILE A LAWSUIT IN COURT.
14.1. Initial Dispute Resolution
The parties shall use their best efforts to engage directly to settle any dispute, claim, question, or disagreement and engage in good faith negotiations which shall be a condition to either party initiating a lawsuit or arbitration.
14.2. Binding Arbitration
If the parties do not reach an agreed upon solution within a period of 30 days from the time informal dispute resolution under the Initial Dispute Resolution provision begins, then either party may initiate binding arbitration as the sole means to resolve claims, subject to the terms set forth below. Specifically, all claims arising out of or relating to these Terms (including their formation, performance and breach), the parties’ relationship with each other and/or your use of the Service shall be finally settled by binding arbitration administered by the American Arbitration Association in accordance with the provisions of its Commercial Arbitration Rules and the supplementary procedures for consumer related disputes of the American Arbitration Association (the “AAA”), excluding any rules or procedures governing or permitting class actions.
The arbitrator, and not any federal, state or local court or agency, shall have exclusive authority to resolve all disputes arising out of or relating to the interpretation, applicability, enforceability or formation of these Terms, including, but not limited to any claim that all or any part of these Terms are void or voidable, or whether a claim is subject to arbitration. The arbitrator shall be empowered to grant whatever relief would be available in a court under law or in equity. The arbitrator’s award shall be written, and binding on the parties and may be entered as a judgment in any court of competent jurisdiction.
The parties understand that, absent this mandatory provision, they would have the right to sue in court and have a jury trial. They further understand that, in some instances, the costs of arbitration could exceed the costs of litigation and the right to discovery may be more limited in arbitration than in court.
14.3. Location
Binding arbitration shall take place in the state of New York. You agree to submit to the personal jurisdiction of any federal or state court in Nõmme linnaosa, Tallinn, in order to compel arbitration, to stay proceedings pending arbitration, or to confirm, modify, vacate or enter judgment on the award entered by the arbitrator.
14.4. Class Action Waiver
The parties further agree that any arbitration shall be conducted in their individual capacities only and not as a class action or other representative action, and the parties expressly waive their right to file a class action or seek relief on a class basis. THE PARTIES AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING.
If any court or arbitrator determines that the class action waiver set forth in this paragraph is void or unenforceable for any reason or that an arbitration can proceed on a class basis, then the arbitration provision set forth above shall be deemed null and void in its entirety and the parties shall be deemed to have not agreed to arbitrate disputes.
14.5. Exception - Litigation of Intellectual Property and Small Claims Court Claims
Notwithstanding the parties' decision to resolve all disputes through arbitration, either party may bring an action in state or federal court to protect its intellectual property rights (“intellectual property rights” means patents, copyrights, moral rights, trademarks, and trade secrets, but not privacy or publicity rights). Either party may also seek relief in a small claims court for disputes or claims within the scope of that court’s jurisdiction.
14.6. 30-Day Right to Opt Out
You have the right to opt-out and not be bound by the arbitration and class action waiver provisions set forth above by sending written notice of your decision to opt-out to the following address: GP Wallet/ConsenSys, 49 Bogart Street, Brooklyn NY 11206 and via email at notices@consensys.net. The notice must be sent within 30 days of September 6, 2016 or your first use of the Service, whichever is later, otherwise you shall be bound to arbitrate disputes in accordance with the terms of those paragraphs. If you opt-out of these arbitration provisions, GP Wallet also will not be bound by them.
14.7. Changes to this Section
GP Wallet will provide 60-days’ notice of any changes to this section. Changes will become effective on the 60th day and will apply prospectively only to any claims arising after the 60th day. For any dispute not subject to arbitration you and GP Wallet agree to submit to the personal and exclusive jurisdiction of and venue in the federal and state courts located in Nõmme linnaosa, Tallinn. You further agree to accept service of process by mail, and hereby waive any and all jurisdictional and venue defenses otherwise available. The Terms and the relationship between you and GP Wallet shall be governed by the laws of Tallinn without regard to conflict of law provisions.
15. General Information
15.1. Entire Agreement
These Terms (and any additional terms, rules and conditions of participation that GP Wallet may post on the Service) constitute the entire agreement between you and GP Wallet with respect to the Service and supersedes any prior agreements, oral or written, between you and GP Wallet. In the event of a conflict between these Terms and the additional terms, rules and conditions of participation, the latter will prevail over the Terms to the extent of the conflict.
15.2. Waiver and Severability of Terms
The failure of GP Wallet to exercise or enforce any right or provision of the Terms shall not constitute a waiver of such right or provision. If any provision of the Terms is found by an arbitrator or court of competent jurisdiction to be invalid, the parties nevertheless agree that the arbitrator or court should endeavor to give effect to the parties' intentions as reflected in the provision, and the other provisions of the Terms remain in full force and effect.
15.3. Statute of Limitations
You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to the use of the Service or the Terms must be filed within one (1) year after such claim or cause of action arose or be forever barred.
15.4. Section Titles
The section titles in the Terms are for convenience only and have no legal or contractual effect.
15.5. Communications
Users with questions, complaints or claims with respect to the Service may contact us at info@dde-ex.com.
`;

export { PrivacyPolicyEnglish, TermsOfUseEnglish };
